---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-conf
data:
  postgres_uri: {{ .Values.env.postgresUri }}
  mongo_uri: {{ .Values.env.mongoUri | quote }}
  report_path: {{ .Values.env.reportPath }}
  log_path: {{ .Values.env.logPath }}
  